### ISSUE TITLE
Implement a Home Page with facebook link

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#107]
## Goal
Create a home page for Guest visitors. This page will be composed of cards representing a news. The card interface is described below. 

A card could be:
- Fetched form the [K-Fêt Facebook Page](https://www.facebook.com/kfetinsalyon/) through Facebook API
- Created by a user (barman or specialAccount with appropriated permissions).

### Front
In sprint 5, we will use [material card](https://material.angular.io/components/card/overview) to display cards.
In next sprints, we will implement a unique card view in order to display custom card in a much better way.

### API EndPoint

- `GET /feed?offset=XX` Get the 40 lastest news including facebook news and custom news with XX offset _(we will define this figure considering ServerMonitoring logs)_. This request have to be cached in the server memory (or in a redisDB?). It is computed every X minutes _(depends of the facebook application limits)_. 

The following endPoint will be implemented in next sprints:
- `POST /feed` Create a card
- `PUT /feed/{id}` Update a card
- `DELETE /feed/{id}` Delete a card
- `GET /feed/categories/` Get all categories.
- `POST /feed/categories/` Post a new category
- `PUT /feed/categories/{id}` Update a new category
- `DELETE /feed/categories/{id}` Delete a new category

### Card Interface
```
{
  title: String,
  content: String, // Markdown content
  createdAt: Date,
  updatedAt: Date,
  date: Date, // Event date or = createdAt date
  pin: Boolean,
  isFacebook: Boolean,
  media: [
      id: Number,
      url: String,
      type: ENUM(video, image),
    }
  ],
  openLink: string,
  categories: [{
      id: Number,
      name: String,
      shortDescription: String,
    }
  ],
};
```
### Facebook edge to card support
For the begining, we have to support only **post**. 
In next sprints, we can implfutherement: **link, status, photo, video, offer**.

**Comment by kistora** [comment]
We schouldn't use facebook API page in the client side.

> https://stackoverflow.com/a/33078837

**Comment by kistora** [comment]
We schould use this module in back. As a result, we fetch the event every X minutes.
https://github.com/kwhitley/apicache

**Comment by kistora** [comment]
Also, this package could be very usefull if we want to simplify calls to the facebook API graph page.
https://www.npmjs.com/package/fb

**Comment by Embraser01** [comment]
Ok, nice job !

I don't have much to say.

For caching:
- Why using redis ? 
- If we want to save post made by a barman, we will need a database, so why not save facebook post ? 
- In this case, we just need to set FB to sent us a notification when a new post is made and just load posts from database (so no cahcing).

For post content:
- I think we should forbid (escape) HTML in the content field.
- If we want to allow it, we could use Markdown

**Comment by Embraser01** [comment]
Also, does we also post the post made through the K-App in Facebook

**Comment by Embraser01** [comment]
Anyway we will use webhooks to detect new post on the FB page: https://developers.facebook.com/docs/graph-api/webhooks/

We will add a new middleware https://github.com/alexcurtis/express-x-hub 

I didn't have time to search for how subscription works, I will do it later

**Comment by kistora** [comment]
@Embraser01 

> Why using redis ?

Use redis could save server RAM: check [ApiCache wiki](https://github.com/kwhitley/apicache#use-with-redis)

> If we want to save post made by a barman, we will need a database, so why not save facebook post ?

Because we have update our database if a Facebook post, link ... is updated or removed. It will be very difficult to maintain. What do you think ?

> we just need to set FB to sent us a notification when a new post is made 

How ? Oh ok you answer that !

> Also, does we also post the post made through the K-App in Facebook ?

No, I don't want to implement it. Maybe someone, one day, will !

> Use markdown instead of HTML

Ok ! Great idea. Is that for security reasons ?

**Comment by Embraser01** [comment]
> Ok ! Great idea. Is that for security reasons ?
Yes, exactly :wink:

> It will be very difficult to maintain. What do you think ?
Actually, with the webhooks system, it will be easy, as it will be quite the same as updating a post from the website.
As I understand:
- At startup, we subscribe to FB for a page,
- Then FB will send updates from the page (create/update/delete/etc...)
- We then just have to call the same services as thus for a post from the webiste

**Comment by kistora** [comment]
## Protocole d'obteintion d'un token d'accès de page illimité (never expired)

https://medium.com/@Jenananthan/how-to-create-non-expiry-facebook-page-token-6505c642d0b1

## DEBUGUEUR DE TOKEN
Pour tester la validiter d'un token et obtenir des informations

https://developers.facebook.com/tools/debug/accesstoken/

J'ai donc pu créer un token illimité mais ne peut pas l'utiliser (cf mon post slack):

> REPORT
> - C'est un coup dur pour l'application K-App & l'intégration des posts facebook !*
> Pour faire simple, Facebook vient tout juste (il y a 2 jours) de restreindre l'accès à son API à cause des attaques de Cambridge Analytica (la société au coeur du scandale). Renseignez vous sur le web !
> L'article officiel sur le blog de facebook (posté le 21 mars). https://newsroom.fb.com/news/2018/03/cracking-down-on-platform-abuse/
> Sinon, voici la capture d'ecran qui illustre la restriction (le token d'accès est valide et la requête est censée renvoyer la totalité des posts facebook de la page de la K-Fêt).
> Bonne nuit

**Comment by Embraser01** [comment]
It's good now, I will start developping it soon

**Comment by Embraser01** [comment]
So... To resume the path to get webhooks notifications from FB:

- [ ] Create a route to verify the challenge (`GET /feed/webhooks`)
- [ ] Create a route to handle updates (`POST /feed/webhooks`)
- [ ] Check for the good X-Hub header

To subscribe for these updates, we have two options:

The first is to directly configure the app through the FB UI, but I don't think it's the best way.

The second way is through the [_subscriptions_](https://developers.facebook.com/docs/graph-api/reference/v2.12/app/subscriptions#publish) edge of FB:
A simple request to `POST /v2.12/{app-id}/subscriptions` with:
- `app_id` which will be pass by the environnement variable `FB_APP_ID`
- `object` the type of object we want (here `page`)
- `callback_url` is `WEB_CONFIG.publicUrl + '/api/feed/webhooks'`
- `fields` a string listing all the fields wanted (separated by `,`)
- `include_values` to `true`
- `verify_token` will be an environnement variable generated at setup
- `access_token` which will be pass by the environnement variable `FB_ACCESS_TOKEN`


To be allowed to do that, the app must have access to the page:

See the official explication to do it directly from the Graph Explorer [here](https://developers.facebook.com/docs/graph-api/webhooks/getting-started/webhooks-for-pages#install-app).

Or follow these instructions (approximatly the same):
(incoming soon..)

**Comment by kistora** [comment]
# Required config
- Configure two facebook app:
	- For dev
	- For prod
- Create facebook dev page
- New ENV VAR:
	- FACEBOOK_APP_SECRET
	- FACEBOOK_APP_ID
	- FACEBOOK_PAGE_ID
- New config var:
	- FACEBOOK_APP_SECRET (depend on FACEBOOK_APP_SECRET on prod & hard coded facebook test app secret on dev)
	- FACEBOOK_APP_ID (depend on FACEBOOK_APP_ID on prod & hard coded facebook test app id on dev)
	- FACEBOOK_PAGE_ID (depend on FACEBOOK_PAGE_ID on prod & hard coded facebook test page id on dev)
	- FACEBOOK_WEBHOOK_URL (depend on PUBLIC_URL on prod & ngrok on dev)

# Access Tokens

## Get a new app access token

TODO

## Get a user access token (with K-Fêt facebook account)

TODO

## Get a page access token**

TODO

# Server process
- Get an app access token
- Check app subscription through `/v3.0/{app-id}/subscriptions` (with an app access token)
	- `object === 'page'`
	- `callback_url === ${WEBHOOK_URL}`
	- `fields include feed`
	- `active === true`
- If check succeed, Stop process
- If check failed,
- Remove all subcriptions through `DELETE /v3.0/{app-id}/subscriptions`
- Get a page access token
- Make sure that page (FACEBOOK_PAGE_ID) have installed the app (FACEBOOK_APP_ID) through `GET /v3.0/{page-id}/subscribed_apps` (with an page access token)
	- Check body.data[x].id === FACEBOOK_APP_ID
- If not, create a subscribed_apps edge for the page through `POST /{page_id}/subscribed_apps` (with a page access token)
- Create a new subcription through `POST /v3.0/{app-id}/subscriptions` (with an app access token)
	- `object = 'page'`
	- `callback_url = ${WEBHOOK_URL}`
	- `fields = [feed]`
	- `active = true`

## Endpoints
	- `GET api/feed/webhook` Verification Request: Verify token + respond with challenge field (to which URL?)
	- `POST api/feed/webhook`Event Notification


spvT4*LcB38Uz]!^

**Comment by kistora** [comment]
# Required config
- Configure two facebook app:
	- For dev
	- For prod
- Create facebook dev page
- New ENV VAR:
	- FACEBOOK_APP_SECRET
	- FACEBOOK_APP_ID
	- FACEBOOK_PAGE_ID
- New config var:
	- FACEBOOK_APP_SECRET (depend on FACEBOOK_APP_SECRET on prod & hard coded facebook test app secret on dev)
	- FACEBOOK_APP_ID (depend on FACEBOOK_APP_ID on prod & hard coded facebook test app id on dev)
	- FACEBOOK_PAGE_ID (depend on FACEBOOK_PAGE_ID on prod & hard coded facebook test page id on dev)
	- FACEBOOK_WEBHOOK_URL (depend on PUBLIC_URL on prod & ngrok on dev)

# Access Tokens

## Get a new app access token

TODO

## Get a user access token (with K-Fêt facebook account)

TODO

## Get a page access token**

TODO

# Server process
- Get an app access token
- Check app subscription through `/v3.0/{app-id}/subscriptions` (with an app access token)
	- `object === 'page'`
	- `callback_url === ${WEBHOOK_URL}`
	- `fields include feed`
	- `active === true`
- If check succeed, Stop process
- If check failed,
- Remove all subcriptions through `DELETE /v3.0/{app-id}/subscriptions`
- Get a page access token
- Make sure that page (FACEBOOK_PAGE_ID) have installed the app (FACEBOOK_APP_ID) through `GET /v3.0/{page-id}/subscribed_apps` (with an page access token)
	- Check body.data[x].id === FACEBOOK_APP_ID
- If not, create a subscribed_apps edge for the page through `POST /{page_id}/subscribed_apps` (with a page access token)
- Create a new subcription through `POST /v3.0/{app-id}/subscriptions` (with an app access token)
	- `object = 'page'`
	- `callback_url = ${WEBHOOK_URL}`
	- `fields = [feed]`
	- `active = true`

## Endpoints
	- `GET api/feed/webhook` Verification Request: Verify token + respond with challenge field (to which URL?)
	- `POST api/feed/webhook`Event Notification

**Comment by kistora** [comment]
What do you think about his ?

![models-class model](https://user-images.githubusercontent.com/29222996/41822946-af976770-77f7-11e8-883d-20afa84496f6.png)

**Comment by Embraser01** [comment]
> Do we need FACEBOOK_APP_ID ENV VAR or a hard coded VAR for dev and prod is enough ?

An env variable is better (no need to edit code in case the app change).

> Do we want that user can update PAGE ID ?

Page Id is not necessary, the application can receive update from every pages that allowed the app.

> ? FACEBOOK_PAGE_ID (in database for client update only in prod ? Security ?)
> ? FACEBOOK_PAGE_ACCESS_TOKEN (in database for client update only in prod ? Security ?)

There is no need for page id informations as the server will handle every post sent through the endpoint (we will consider it as coming from the K-Fêt page).

> New config var: ... 

I think we will rely only on ENV variables for dev config because every token is sensible informations and should not be commit. And we will add a failsafe if there is no TOKEN (no facebook feed in this case). And still no page IDs :smiley:

> Access Tokens

I think this is for managing the page, but we can't get webhooks from here...

> Server Process

I think we shouldn't install the apps from the server. It's a one time operation and should be done by the administrator of the page.

If we have some problems with the subscription edge, we could send an email to the webmaster with some logs describing the issue. This means that we don't know the page, but only the FB app.

> GET api/feed/webhook : Verification Request: Verify token + respond with challenge field (to which URL?)

We respond to the request (there isn't another request made).

> Models

Do we need a category? (I would say yes probably)

Otherwise it looks good, anyway it is the model sent by the webhook no?

**Comment by Embraser01** [comment]
Let's close this as it's no longer the goal of the K-App (maybe we can do something like this in https://github.com/K-Fet/kfet-insa.fr).
Feel free to re-open it if it still is :wink:
