### ISSUE TITLE
Permission EndPoints

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#108]
- [ ] GET: `/permissions`
- [ ] ~~POST: `/permissions`~~ Discussion ...
- [ ] ~~PUT: `/permissions/{id}`~~ Discussion ...
- [ ] ~~DELETE: `/permissions/{id}`~~ Discussion ...

**Comment by kistora** [comment]
@Embraser01 what do you think about `POST` `PUT` & `DELETE` end points ?

**Comment by Embraser01** [comment]
They are all useless

But we have to add to `_embedded` the relationship with permissions in `SpecialAccount` & `Role`
