### ISSUE TITLE
Password managment

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#113]
All scheme are available in in the [draw.io scheme](https://drive.google.com/file/d/1Fol4GJ_6PWvoBeKzNar40ky3Mlw2IpJ4/view?usp=sharing)

### BackEnd
- [x] Implement node mailer module in back
- [x] Change `ConnectionInformation` model: passwordToken, usernameToken, usernameTokenExpiration
- [ ] Implement `POST /api/auth/reset-password`, see swagger
- [ ] Implement `POST /api/auth/username-verification`, see swagger
- [ ] Check `PUT /me`, `PUT /barmen/{id}`, `PUT /specialaccounts/{id}` and implement `specialaccount:force-code-reset` permission.
- [ ] Remove password field for update (JOI)
- [ ] Verify old password for a password update (only through `PUT /me`) See #134 for front issue @mickaelgadoud 

### FrontEnd
- [x] Implement #123 
- [x] Reset password dialog
- [x] Define password component
- [x] Email verification component
- [x] UPDATE `barman-new`, `barman-edit`, `special-account-new` & `special-account-edit`

### Other
- [x] Configure `no-reply@kfet-insa.fr`. This address mustn't receive any mail.

**Comment by kistora** [comment]
I've finished front side :) See #143

**Comment by Embraser01** [comment]
I propose to change routes:
POST /api/reset-password -> POST /api/auth/reset-password
POST /api/email-verification -> POST /api/auth/email-verification

What do you say ?

**Comment by Embraser01** [comment]
Also, we have a route to `PUT /api/auth/reset-password` which will define the password.

Also, I think this have to be the *only* way to define the password!

Any other way don't allow password fields
