### ISSUE TITLE
Create a TODO list app for each Kommissions

### ISSUE THREAD

**Issue by Embraser01** [K-Fet/K-App#164]
We can create a TODO List for each Kommission like Trello already propose...

We have to define which feature we want:
The minimum is (IMO):
- A ordered list of things to do
- Possibilities to set a state for a task (Work in progress, Done, ...)
- A due date
- People assigned

**Comment by ClementGuittat** [comment]
Can we talk about this tomorrow because i don't really understand the issue. Thx

**Comment by ClementGuittat** [comment]
Alors je vous fait une petite review de ce que j'ai pensé par rapport à ces todo list en sachant que j'ai vu ça sous l'angle qu'une Todo-list appartenait à une kommission (on peut voir ça sous la forme qu'une Todo-list appartient à un événement et dans ce cas chaque kommission peut posséder plusieurs Todo-list ). 
Premièrement, petit point voc : dans la suite du texte une **Todo-List** correspondra à une sorte de tableau où il y aura toutes les **taches** à faire pour les barmen d'une kommission.
Dans les faits, un barman appartient à (au moins ou exactement ???) une kommission par exemple Communication. Ce barman pourra voir toutes les tâches de la Toto-List Communication. 
Par souci de simplification (pas besoin d'implémenter les permissions), tous les barmen d'une kommission pourront ajouter une tache à la Todo-List, modifier une tache et son état (en cours, non commencé, annulé ...) et enfin la clôturer. 
Pour les tâches, je trouvais aussi stylé de pouvoir avoir une deadLine de fin et avoir un petit curseur qui avance pour voir le temps qu'il reste ou un compteur (bien stressant 😂). On pourrait aussi avoir un bouton qui permette de voir une tâche plus précisément avec une description précise de ce qu'il y a à faire et des commentaires par exemple. 
Et enfin, il faudrait être capable d'assigner un ou plusieurs barmen de la kommission à une tâche. 

## End Points
- GET /api/TODO (permet de récupérer toutes les Todo-List de toutes les kommissions si par exemple le président ou admin veut voir si tout avance bien). 
- GET /api/TODO/:id (permet de récupérer une Todo-list lié à une kommission en particulier et l'afficher en front pour les barmen appartenant à cette kommission afin qu'ils voient toutes leurs tâches)
- GET /api/TODO/:id/Tache/:tacheId (permet de récupérer une tâche précise d'une Todo-list précise afin d'avoir plus d'infos sur cette tâche comme description ou commentaires)
- POST /api/TODO/:id/Tache (permet de créer une tache pour une todo-list)
- PUT /api/TODO/:id/Tache/:tacheId (permet de modifier une tache d'une todo-list par exemple sa date de fin, sa description ou son état) 
- DELETE /api/TODO/:id/Tache/:tacheId (permet de supprimer une tache d'une todo-list et donc de ne plus la voir affichée)
- POST /api/kommissions/:id/TODO (permet de créer une Todo-List pour une kommission) 

PS : j'ai fait le modèle UML je vous le transmet un peu plus tard

**Comment by ClementGuittat** [comment]
<img width="590" alt="capture d ecran 2018-05-03 a 16 05 58" src="https://user-images.githubusercontent.com/32964240/39581457-e5c1c3a2-4eeb-11e8-9568-ef311d721b04.png">

**Comment by ClementGuittat** [comment]
J'ai fait ça rapidement je vous avoue et je maitrise pas trop :p

**Comment by kistora** [comment]
J'ai pris le temps de lire un peu ta proposition. Plusieurs petites remarques:

- Il faudrait ajouter les fields automatiques createdAt & updatedAt (très facilement implementables avec sequelize).
- Pourquoi avoir une table TODO alors qu'il n'y a rien excepté l'ID ? Je lierais directement l'objet `Tache` (`Task` en vrai) à l'objet `Kommission`.
- C'est effectivement un schéma en UML mais il faut maintenant que tu traduises ça dans un dans une table en relationnel: c'est pas possible d'avoir un attribut `assigné: Barman[]`. Il faut que tu utilises les tables wrapper (cf drive/K-App/Diagrammes/model).
- A propos des EndPoints:
	- Dans un premier temps, les specifications REST nous obligent a mettre toutes nos routes sous le format `/api/nomElementPluriel/...`
	- En suivant le résonnement décris ci dessus, je changerais les endpoints de `/api/TODO...` vers `/api/kommissions/:id/tasks...` et donc je supprimerai intermédiaire que tu as appelé `TODO`.

**Du coup, je te demande de:**
1. Compléter les schéma model du drive en fonction de ce que tu viens de décrire (tu peux faire une copie si tu n'es pas sur). N'oublie pas de traduire tes attributs en anglais :)
2. Revoir les endPoints.

Quand c'est terminé, met un commentaire ici!

**Comment by ClementGuittat** [comment]
## End Points
- GET /api/kommissions/:id/tasks (permet de récupérer toutes les tâches liées à une kommission en particulier)
- GET /api/kommissions/:id/tasks/:taskid (permet de récupérer une tâche précise d'une kommission afin d'avoir plus d'infos sur cette tâche comme description ou commentaires)
- POST /api/kommissions/:id/tasks (permet de créer une tache pour une kommission)
- PUT /api/kommissions/:id/tasks/:taskid (permet de modifier une tache d'une kommission par exemple sa date de fin, sa description, son état ou d'assigner une nouvelle personne) 
- DELETE /api/kommissions/:id/tasks/:taskid (permet de supprimer une tache d'une kommission et donc de ne plus la voir affichée)

**Comment by kistora** [comment]
On un peu simplifier:

- GET /api/kommissions/:id/tasks (permet de récupérer toutes les tâches liées à une kommission en particulier) **OK**
- **GET /api/tasks/:taskId** (permet de récupérer une tâche précise afin d'avoir plus d'infos sur cette tâche comme description ou commentaires)
- POST /api/kommissions/:id/tasks (permet de créer une tache pour une kommission) **OK**
- **PUT /api/tasks/:taskId** (permet de modifier une tache par exemple sa date de fin, sa description, son état ou d'assigner une nouvelle personne.
- **DELETE /api/tasks/:taskId** (permet de supprimer une tache d'une kommission et donc de ne plus la voir affichée)

Tu peux partir la dessus (en complétant swagger ? ;), Dis moi si t'as pas les droits).

**Comment by Embraser01** [comment]
Un barman devrait avoir la possibilité d'afficher ses tâches (en triant par kommissions)

**Comment by kistora** [comment]
We have discussed with @ClementGuittat 

- [ ] *Step 1*: Finish kommission-view component
- [ ] *Step 2*: Implement popup with more information when a task has been clicked/touched in kommission-view component
- [ ] *Step 3*: Display tasks of the connected barman on his/her home page

**Comment by kistora** [comment]
Please see PR #273 ! I've worked on it :)
