### ISSUE TITLE
Services doesn't fit well

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#237]
In `planning` & `plan-my-services` components

![image](https://user-images.githubusercontent.com/29222996/40228672-35aa6606-5a92-11e8-9b61-ce182765b910.png)

**Comment by bdbipbip** [comment]
K-App/client/src/app/services/planning/planning.component.html 

Line 25:  Avec <span *ngFor="let barman of service.barmen">{{barman.nickname}}</span>

==> Avec <span *ngFor="let barman of service.barmen">{{barman.nickname}}, </span>

J'ai bon ?
