### ISSUE TITLE
Increase token expiration date

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#250]
Client requirement.

It's annoying to log in every time you lunch the app !

Token expiration date schould be a day.

**Comment by Embraser01** [comment]
Ok, I will look into this

**Comment by Embraser01** [comment]
So:

Just increasing the validation to 1 day is not so good as it will (for example) not update permissions as soon as wanted...

Anyway this problem will always be there I think 😢 

But I think we could change the way we do the authentication:

- Let the client decide the duration of his token (with some limitation oc)
- Add a **Remember Me** checkbox in the login page
- If checked, set a delay of 1 month (more or less) and save it in `localStorage`
- Else, set a delay of 1 day and save it in `sessionStorage`

This will allow to customize each client (in case of a Mobile App or anything else).
And we should remove refresh functionality

## Permissions

When I decided to add permissions in the JWT, I was wrong. I think we should always have the most up to date rights.

If somehow, we need to generate a token with special permissions, we can still use the field `permissions` of the JWT (or better, a field `apiPerms` or equivalent).

## Implied changes

- Remove refresh function
- Add a duration parameter to the `/auth/login` endpoint
- Change the client with:
	* Add `Remember Me` checkbox
	* Send the corresponding request
	* Choose the storage to use
	* At loading, load the token (first localStorage then sessionStorage)
- Change the jwt middleware to:
	* Load permissions from database to `req.user.permissions`
	* If a field `apiPerms` is present (event empty):
		- Do something like `req.user.permissions = req.user.permissions.filter(p => apiPerms.include(p))`.

**Comment by kistora** [comment]
- Remove refresh function **OK**
- Add a duration parameter to the `/auth/login` endpoint **We schould set a default value for the moment**
- Change the client with:
   - Add Remember Me checkbox **OK**
   - Send the corresponding request **OK**
   - Choose the storage to use **OK**
   - **We also need to fetch the connected user permissions through a new endPoint `/me/permissions?`**
   - At loading, load the token (first localStorage then sessionStorage) **OK**
- Change the jwt middleware to:
   - Load permissions from database to req.user.permissions **OK**
   - If a field apiPerms is present (event empty):  **NOT OK, this feature is not needed**
      - Do something like req.user.permissions = req.user.permissions.filter(p => apiPerms.include(p)).

**Comment by Embraser01** [comment]
* The default value would a front value anyway (depending on the remember me value)
* We should block max value for now (e.g.: max 1 month)
* Permissions could be sent with the /me data
* For the `apiPerms` part it was a __just in case__ solution. Alway better to think about it now 😉

**Comment by kistora** [comment]
- I don't understand the default value story :) We will talk about it this evening :)
- We should block max value for now (e.g.: max 1 month). **OK**
- Permissions could be sent with the /me data **OK**
- Ok for the apiPrems but we won't implement it for now

**Comment by kistora** [comment]
Expiration date is hardcoded in front side as a default value.
- If remember me is unchecked => sessionStorage, 1jour
- If remember me is checked => localStorage, 1month
