### ISSUE TITLE
Automatic alphabetical order for every table

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#261]
**Is your feature request related to a problem? Please describe.**
For now, UX is not very intuitive about table default sort.

**Describe the solution you'd like**
Default alphabetical order for every table.

**Describe alternatives you've considered**
We schould discuss if we compute the sort on the back side or on the front side. What do you think @Embraser01 ?

**Comment by Embraser01** [comment]
We should do it on the back side with sequelize, it's quite easy... But we could allow ordering also in front, so the user can sort his able as he want
