### ISSUE TITLE
Information kezia 2

### ISSUE THREAD

**Issue by WENKz** [K-Fet/K-App#408]
Bonjour,
Je tiens à m'excuser d'avance pour poster min ticket, je n'ai pas trouvé d'autre moyen pour vous contacter.
Je suis entrain de travailler sur un projet avec Kezia 2 (le fun).
J'ai remarqué que dans l'un de vos précédents projet vous avez essayé de vous connecter au server hfsql, est ce possible d'avoir plus d'information ?
Je vous remercie d'avance

Cordialement,

**Comment by Embraser01** [comment]
Bonjour, 

Effectivement, j'ai réussi à charger l'historique des transactions faite sur Kezia II en accédant directement à la DB HFSQL du logiciel. Le serveur HFSQL a un driver [ODBC](https://fr.wikipedia.org/wiki/Open_Database_Connectivity) qui me permet de faire mes requêtes SQL depuis JS (à travers le package [odbc](https://github.com/markdirish/node-odbc/). 

Exemple d'une requête pour récupérer les ventes avec l'id du produit, le nom du produit, la quantité et la date : https://github.com/K-Fet/k-app-connector-kezia-ii/blob/master/src/events/reader/index.js

**Comment by WENKz** [comment]
Merci pour ce retour, 
En fait j'ai fait des tentatives de connection avec un package odbc, mais il semble qu'il faut absolument configurer (je ne sais comment) le driver hfsql, vous êtes sur un environnement Windows ou Linux ? (sur Mac os il semble que ce ne soit pas possible car hfsql pas dispo) j'envisage donc de monter une image docker histoire de pouvoir et essayer config le driver.

**Comment by Embraser01** [comment]
J'ai testé sur Windows pour éviter tout problème (le script étant déployé sur un PC Windows). Je sais qu'il y a des drivers pour Linux et Mac OS (ils sont indiqués dans le README du package odbc) mais j'ai jamais essayé
