### ISSUE TITLE
Generate services with template managment

### ISSUE THREAD

**Issue by Embraser01** [K-Fet/K-App#49]
We should be able to generate services for a long period of time:

We have a lot of option:
- Use online API to get holidays, public holiday, etc...
- Have a template for a week
- Be able to create other services (special, etc...)

**Comment by Embraser01** [comment]
After some discussion, we will do this:

- Create two endpoints:
    - GET: `/services/template` ==> Return an array of services for a template week
    - PUT: `/services/template` ==> Set a new array of services for a template week
- In front, the user will be able to choose the template, and edit the week as wanted

N.B.: Block the number of template to one for now

Only the admin (or equivalent) will be able to do that.
Nothing is generated in back, the front will have to take care of finding the next monday, and update `startDate` and `endDate`.

In order to generate a week, the front will have to send a lot of requests (~10),
one for each services. We could seek for a better way to do that?

**Comment by kistora** [comment]
For the template model:
