### ISSUE TITLE
Associations changes not visible when doing a PUT

### ISSUE THREAD

**Issue by ClementGuittat** [K-Fet/K-App#89]
When doing a PUT on Barman (for example), if i am using a parameter _embedded in the body and that i want to add a Kommission (same for other parameter like roles), it will be correctly taken into account in the database but the barman displayed by this request won't have any Kommissions. I will have to request this barman in particular to see that the kommission is well associated to the barman.

**Comment by Embraser01** [comment]
So after a little digging, you will have to call [`instance.reload()`](http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-reload) at the end of the service
