### ISSUE TITLE
Delete connection information if a barman / special account is deleted

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#96]
### Current behaviour
The calls `DELETE /api/barmen/{id}` or `DELETE /api/specialaccounts/{id}` delete the barman / special account with the id passed in the URL.

### Expected behaviour
The connectionAssociation have to be deleted too.

**Comment by Embraser01** [comment]
See `// FIXME` in barmanService#deleteBarman()

**Comment by Embraser01** [comment]
Fix with #92
